services:
  blog:
    build:
      context: .
    container_name: blog
    depends_on:
      - blogdatabase
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://blogdatabase:5432/blog
    ports:
      - "8080:8080"
    volumes:
      - /var/www/upload:/var/www/upload
    networks:
      - mynetwork

  blogdatabase:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    image: postgres
    container_name: blogdatabase
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blog
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # 🔥 Kalıcı veri deposu ekledik
    networks:
      - mynetwork


volumes:
  postgres_data:  # 🔥 Postgres için kalıcı veri deposu
  upload-data:


networks:
  mynetwork:
    driver: bridge
